routes/web.php
<?php

use App\Models\Post;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TagController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\FrontEndController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\ContactController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layouts.master');
});
// Route::get('/post', function () {
//     return view('website.contact');
// });

Auth::routes();
//forntend controller
Route::get('/home',[FrontEndController::class, 'home'])->name('website.home');
Route::get('/about',[FrontEndController::class, 'about'])->name('website.about');
Route::get('/category/{slug?}',[FrontEndController::class, 'category'])->name('website.category');
Route::get('/contact',[FrontEndController::class, 'contact'])->name('website.contact');
Route::post('/contactStore',[FrontEndController::class, 'sendMessage'])->name('contact.store');
Route::get('/post/{slug?}',[FrontEndController::class, 'post'])->name('website.post');
Route::get('/userDetails/{slug?}',[FrontEndController::class, 'userDetails'])->name('website.userDetails');
Route::get('/blog-home',[IndexController::class,'index'])->name('blog-home');



// admin panel route
Route::group(['prefix'=>'admin', 'middleware'=>['auth']], function(){
    Route::get('/test', function () {
        return view('admin.dashboard.index');
    });
    Route::get('/delete',[ContactController::class,'delete'])->name('contact.destroy');
    Route::resource('/category',CategoryController::class);
    Route::resource('/tag',TagController::class);
    Route::resource('/post',PostController::class);
    Route::resource('/user',UserController::class);
    Route::resource('/contacts',ContactController::class);

    Route::get('/profile',[UserController::class,'profile'])->name('user.profile');
    Route::get('/setting',[SettingController::class,'index'])->name('setting.index');
    Route::post('/settingUpdate',[SettingController::class,'update'])->name('setting.update');
    Route::get('/imageCreate',[\App\Http\Controllers\MultipleImageController::class,'create'])->name('multipleImage.create');
    Route::post('/multipleImage',[\App\Http\Controllers\MultipleImageController::class,'Store'])->name('multipleImage.store');
    //message Route

    Route::get('/contactShow/{id}',[\App\Http\Controllers\ContactController::class,'show'])->name('contact.show');
});
Route::get('/logout', function(){
    Auth::logout();
    return Redirect::to('login');
 });
Route::get('/test',function(){
    $posts = Post::all();
    $id =172;
    foreach($posts as $post){
        $post->image = "https://picsum.photos/id/".$id."/640/480.jpg";
        $post->update();
        $id++;
    }
    return $posts;
});
Route::get('/clear', function(){
    \Artisan::call('route:clear');
    \Artisan::call('config:cache');
    \Artisan::call('cache:clear');
});

app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use HasFactory;

    protected $fillable =[
        'name',
        'slug',
        'description',
    ];
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use Session;
use App\Models\Category;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Http\Requests\CategoryStoreRequest;
use App\Http\Requests\CategoryUpdateRequest;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::orderBy('id','DESC')->paginate(20);
        return view('admin.category.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryStoreRequest $request)
    {
        $category = Category::create([
            'name' => $request->name,
            'slug'=> Str::slug($request->name,'_'),
            'description'=>$request->description,
        ]);
        Session::flash('status','Data Successfully iserted');
        return redirect('admin/category/create');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
       $data['category'] = $category;
       return view('admin.category.edit')->with($data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryUpdateRequest $request, Category $category)
    {
        $data = $request->Validated();
        $data['slug'] = Str::slug($request->name,'_');
        $data['description'] = $request->description;
        $category->update($data);
        Session::flash('status','Data Successfully updated');
        return redirect('admin/category');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
      if ($category) {
        $category->delete();
        Session::flash('status','Data Successfully Deleted');
        return redirect('admin/category');

      }
    }
}

resources/views/admin/category/create.blade.php
@extends('layouts.admin')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Create Category</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('blog-home') }}">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v1</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="d-flex justify-content-between item-center">
                    <h3 class="card-title">Category Create</h3>
                    <a href="{{ URL::to('admin/category') }}" class="btn btn-primary">Category List</a>
                </div>
            </div>
<!--             @if (Session::has('status'))
                <p class="alert alert-success">{{ Session::get('status') }}</p>
            @endif -->
            <div class="row">
                <div class="col-md-7">
                    <form method="POST" action="{{ route('category.store') }}">
                        @csrf
                        @method('POST')
                        @include('admin.category.form-category',['button'=>'Save'])
                    </form>
                </div>
            </div>

        </div>

        <div>
        @endsection

resources/views/admin/category/edit.blade.php
@extends('layouts.admin')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Create Category</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('blog-home') }}">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v1</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="d-flex justify-content-between item-center">
                    <h3 class="card-title">Category Edit - {{$category->name}}</h3>
                    <a href="{{ URL::to('admin/category') }}" class="btn btn-primary">Category List</a>
                </div>
            </div>
<!--             @if (Session::has('status'))
                <p class="alert alert-success">{{ Session::get('status') }}</p>
            @endif -->
            <div class="row">
                <div class="col-md-7">
                    <form action="{{ route('category.update',[$category->id])}}" method="POST">
                        @csrf
                        @method('PUT')
                        @include('admin.category.form-category',['button'=>'Update'])
                    </form>
                </div>
            </div>

        </div>

        <div>
        @endsection

resources/views/admin/category/form-category.blade.php
<div class="card-body">
    <div class="form-group">
        <label for="exampleInputname">Name</label>
        <input type="text" name="name" class="form-control" id="exampleInputName"
            placeholder="Enter Category Name" value="{{ isset($category) ? $category->name : old('name')}}">
        @error('name')
            <span class="text-danger">{{ $message }}</span>
        @enderror
    </div>
    <div class="form-group">
        <label for="exampleInputDescription">Description</label>
        <textarea name="description" id="" cols="60" rows="4" class="form-control">{{isset($category)? $category->description : old('description')}}</textarea>
    </div>
</div>
<div class="card-footer">
    <button type="submit" class="btn btn-primary">{{$button}}</button>
</div>

resources/views/admin/category/index.blade.php
@extends('layouts.admin')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Category List</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('blog-home') }}">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v1</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="d-flex justify-content-between item-center">
                    <h3 class="card-title">Category List</h3>
                    <a href="{{ route('category.create') }}" class="btn btn-primary">Create Category</a>
                </div>

                <!-- <div class="card-tools">
                    <ul class="pagination pagination-sm float-right">
                        <li class="page-item"><a class="page-link" href="#">«</a></li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link" href="#">»</a></li>
                    </ul>
                </div> -->
            </div>
            <!-- /.card-header -->
            <div class="card-body p-0">
                <table class="table">
                    <thead>
                        <tr>
                            <th style="width: 10px">ID</th>
                            <th>Name</th>
                            <th>Slug</th>
                            <th>Description</th>
                            <th>Post Count</th>
                            <th style="width: 40px">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if ($categories->count() > 0)
                            @foreach ($categories as $data)
                                <tr>
                                    <td>{{ $data->id }}</td>
                                    <td>{{ $data->name }}</td>
                                    <td>{{ $data->slug }}</td>
                                    <td>{{ $data->description }}</td>
                                    <td>{{ $data->id }}</td>
                                    <td class="d-flex">
                                        <a href="{{ route('category.edit', [$data->id]) }}"
                                            class="btn btn-sm btn-primary mr-1"><i class="fas fa-edit"></i></a>
                                        <form action="{{ route('category.destroy', [$data->id]) }}}" class="mr-1"
                                            method="POST">
                                            @method('DELETE')
                                            @csrf
                                            <button class="btn btn-sm btn-danger "><i class="fas fa-trash"></i></button>
                                        </form>

                                        <a href="{{ route('category.destroy', [$data->id]) }}}"
                                            class="btn btn-sm btn-success mr-1"><i class="fas fa-eye"></i></a>
                                    </td>
                                </tr>
                                @endforeach
                            @else
                                <tr>
                                    <td colspan="5">
                                        <h5 class="text-center">No Category found</h5>
                                    </td>
                                </tr>
                            @endif
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
    </div>
    <!-- /.card -->
    </div>
    <div>
    @endsection