routes/web.php
<?php

use App\Models\Post;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TagController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\FrontEndController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\ContactController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layouts.master');
});
// Route::get('/post', function () {
//     return view('website.contact');
// });

Auth::routes();
//forntend controller
Route::get('/home',[FrontEndController::class, 'home'])->name('website.home');
Route::get('/about',[FrontEndController::class, 'about'])->name('website.about');
Route::get('/category/{slug?}',[FrontEndController::class, 'category'])->name('website.category');
Route::get('/contact',[FrontEndController::class, 'contact'])->name('website.contact');
Route::post('/contactStore',[FrontEndController::class, 'sendMessage'])->name('contact.store');
Route::get('/post/{slug?}',[FrontEndController::class, 'post'])->name('website.post');
Route::get('/userDetails/{slug?}',[FrontEndController::class, 'userDetails'])->name('website.userDetails');
Route::get('/blog-home',[IndexController::class,'index'])->name('blog-home');



// admin panel route
Route::group(['prefix'=>'admin', 'middleware'=>['auth']], function(){
    Route::get('/test', function () {
        return view('admin.dashboard.index');
    });
    Route::get('/delete',[ContactController::class,'delete'])->name('contact.destroy');
    Route::resource('/category',CategoryController::class);
    Route::resource('/tag',TagController::class);
    Route::resource('/post',PostController::class);
    Route::resource('/user',UserController::class);
    Route::resource('/contacts',ContactController::class);

    Route::get('/profile',[UserController::class,'profile'])->name('user.profile');
    Route::get('/setting',[SettingController::class,'index'])->name('setting.index');
    Route::post('/settingUpdate',[SettingController::class,'update'])->name('setting.update');
    Route::get('/imageCreate',[\App\Http\Controllers\MultipleImageController::class,'create'])->name('multipleImage.create');
    Route::post('/multipleImage',[\App\Http\Controllers\MultipleImageController::class,'Store'])->name('multipleImage.store');
    //message Route

    Route::get('/contactShow/{id}',[\App\Http\Controllers\ContactController::class,'show'])->name('contact.show');
});
Route::get('/logout', function(){
    Auth::logout();
    return Redirect::to('login');
 });
Route::get('/test',function(){
    $posts = Post::all();
    $id =172;
    foreach($posts as $post){
        $post->image = "https://picsum.photos/id/".$id."/640/480.jpg";
        $post->update();
        $id++;
    }
    return $posts;
});
Route::get('/clear', function(){
    \Artisan::call('route:clear');
    \Artisan::call('config:cache');
    \Artisan::call('cache:clear');
});

app/Models/Post.php
<?php

namespace App\Models;

use App\Models\Tag;
use App\Models\User;
use App\Models\Category;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Factories\HasFactory;

class Post extends Model
{
    use HasFactory;
    protected $fillable=['title','category_id','image','description'];
    protected $gurded = ['created_at','updated_at'];
    protected $dates = ['published_at'];
    // $fillable = [

    // ];
    public function category(){
      return $this->belongsTo(Category::class);
    }
    public function user(){
      return $this->belongsTo(User::class);
    }
    public function tags(){
      return $this->belongsToMany(Tag::class);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Session;
use Carbon\Carbon;
use App\Models\Tag;
use App\Models\Post;
use App\Models\Category;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Http\Requests\PostStoreRequest;
use App\Http\Requests\PostUpdateRequest;

class PostController extends Controller
{

    public function index()
    {
        $posts = Post::all();
        return view('admin.post.index',compact('posts'));
    }

  
    public function create()
    {
        $data['categories'] = Category::all();
        $data['tags'] = Tag::all();
        return view('admin.post.create')->with($data);
    }

   
    public function store(PostStoreRequest $request)
    {
       $post = $request->validated();
       $post = new Post();
       $post->title = $request->title;
       $post->slug = Str::slug($request->title,'_');
       if($request->file('image')){
            $file= $request->file('image');
            $filename= date('YmdHi').$file->getClientOriginalExtension();
            $file-> move(public_path('public/post'), $filename);
            $post['image']= $filename;
        }
       $post->description = $request->description;
       $post->category_id = $request->category_id;
       $post->user_id =auth()->user()->id;
       $post->published_at = Carbon::now();
       $post->save();
       $post->tags()->attach($request->tags);
       Session::flash('status','Post Create Successfully');
       return redirect('admin/post');



    }


    public function show(Post $post)
    {
        return view('admin.post.show',compact('post'));
    }

 
    public function edit(Post $post)
    {
      $categories= Category::all();
      $tags = Tag::all();
      return view('admin.post.edit',compact('categories','post','tags'));
    }


    public function update(PostUpdateRequest $request,Post $post)
    {
       $data= $request->validated();
       $data['slug'] = Str::slug($request->title,'_');
        $post->tags()->sync($request->tags);
       if($request->file('image')){
            $file= $request->file('image');
            $filename= date('YmdHi').$file->getClientOriginalName();
            $file-> move(public_path('public/post'), $filename);
            $data['image']= $filename;
        }else{
            $data['image'] = $post->image;
        }
       
       $post->update($data);
       Session::flash('status','Post Updated Successfully');
       return redirect()->route('post.index');
    }

 
    public function destroy(Post $post)
    {
        if ($post) {
            $post->delete();
            Session::flash('status','Data Successfully Deleted');
            return redirect('admin/post');
    
          }
    }
}

resources/views/admin/post/create.blade.php
@extends('layouts.admin')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Create post</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('blog-home') }}">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v1</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="d-flex justify-content-between item-center">
                    <h3 class="card-title">post Create</h3>
                    <a href="{{ URL::to('admin/post') }}" class="btn btn-primary">post List</a>
                </div>
            </div>
            <!--             @if (Session::has('status'))
    <p class="alert alert-success">{{ Session::get('status') }}</p>
    @endif -->
            <div class="row">
                <div class="col-md-7">
                    <form method="POST" action="{{ route('post.store') }}" enctype="multipart/form-data">
                        @csrf
                        @include("admin.post.form-post",['button'=>'Save'])
                    </form>
                </div>
            </div>

        </div>
        
        <div>
        @endsection

resources/views/admin/post/edit.blade.php
@extends('layouts.admin')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Create post</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('blog-home') }}">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v1</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="d-flex justify-content-between item-center">
                    <h3 class="card-title">post Create</h3>
                    <a href="{{ URL::to('admin/post') }}" class="btn btn-primary">post List</a>
                </div>
            </div>
            @if (Session::has('status'))
                <p class="alert alert-success">{{ Session::get('status') }}</p>
            @endif
            <div class="row">
                <div class="col-md-7">
                    <form action="{{ route('post.update', [$post->id]) }}" enctype="multipart/form-post" method="POST">
                        @csrf
                        @method('PUT')
                        @include('admin.post.form-post', ['button' => 'Update'])
                    </form>
                </div>
            </div>
        </div>
        </div>
    @endsection

resources/views/admin/post/form-post.blade.php
<div class="card-body">
    <div class="form-group">
        <label for="exampleInputTitle">Title</label>
        <input type="text" name="title" class="form-control" value="{{ isset($post) ? $post->title : old('title') }}"
            id="exampleInputTitle" placeholder="Enter Post Ttile">
        @error('title')
            <span class="text-danger">{{ $message }}</span>
        @enderror

    </div>
    <div class="form-group">
        <label for="exampleInputCategory">Post Category</label>
        <select name="category_id" id="category" class="form-control" value="{{ old('category') }}">
            <option selected disabled style="display: none;">Select Category</option>
            {{-- @if ($categories->count() > 0)
                        @foreach ($categories as $c)
                            <option value="{{ $c->id }}" {{ isset($post) && $post->category_id == $c->id ? 'selected' : '' }} >
                                {{ $c->name }}
                            </option>
                        @endforeach
                    @else
                    @endif --}}
            @forelse ($categories as $c)
                <option value="{{ $c->id }}"
                    {{ isset($post) && $post->category_id == $c->id ? 'selected' : '' }}>
                    {{ $c->name }}
                </option>
            @empty
            @endforelse
        </select>
        @error('category_id')
            <span class="text-danger">{{ $message }}</span>
        @enderror


      
    </div>
    <div class="form-group">
                @if (isset($post))
                @foreach ($tags as $tag)
                <div class="custom-control custom-checkbox">
                    <input class="custom-control-input" type="checkbox" name="tags[]" id="tag{{$tag->id}}" value="{{$tag->id}}" 
                    @foreach ($post->tags as $t )
                        {{ $tag->id == $t->id ? 'checked' : ''}}
                    @endforeach
                    >
                    <label for="tag{{$tag->id}}" class="custom-control-label">{{$tag->name}}</label>
                </div>
                @endforeach
                @else
                @foreach ($tags as $tag)
                <div class="custom-control custom-checkbox">
                    <input class="custom-control-input" type="checkbox" name="tags[]" id="tag{{$tag->id}}" value="{{$tag->id}}">
                    <label for="tag{{$tag->id}}" class="custom-control-label">{{$tag->name}}</label>
                </div>
                @endforeach
                @endif
                
               
                
            

            {{-- <div class="custom-control custom-checkbox">
                <input class="custom-control-input" type="checkbox" id="customCheckbox1{{$tag->id}}" value="option{{$tag->id}}">
                <label for="customCheckbox1{{$tag->id}}" class="custom-control-label">Custom Checkbox</label>
              </div> --}}
       
    </div>
    <div class="form-group">
        <label for="exampleInputImage">Image</label>
        <div class="custom-file">
            <input type="file" class="custom-file-input" id="customFile" name="image">
            <label class="custom-file-label" for="customFile">Choose file</label>
        </div>
        @error('image')
            <span class="text-danger">{{ $message }}</span>
        @enderror
    </div>
    <div class="form-group">
        <label for="exampleInputDescription">Description</label>
        <textarea name="description" id="" cols="60" rows="4"
            class="form-control">{{ isset($post) ? $post->description : old('description') }}</textarea>
    </div>
    @error('description')
        <span class="text-danger">{{ $message }}</span>
    @enderror
</div>
<div class="card-footer">
    <button type="submit" class="btn btn-primary">{{ $button }}</button>
</div>

resources/views/admin/post/index.blade.php
@extends('layouts.admin')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">post List</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('blog-home') }}">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v1</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="d-flex justify-content-between item-center">
                    <h3 class="card-title">post List</h3>
                    <a href="{{ route('post.create') }}" class="btn btn-primary">Create post</a>
                </div>

                <!-- <div class="card-tools">
                    <ul class="pagination pagination-sm float-right">
                        <li class="page-item"><a class="page-link" href="#">«</a></li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link" href="#">»</a></li>
                    </ul>
                </div> -->
            </div>
            <!-- /.card-header -->
            <div class="card-body p-0">
                <table class="table">
                    <thead>
                        <tr>
                            <th style="width: 10px">ID</th>
                            <th>Image</th>
                            <th width="400px" style="float: left;text-align: left;">Title</th>
                            <th>Tag's</th>
                            <th>Categroy</th>
                            <th>Author</th>
                            <th style="width: 40px">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if ($posts->count() > 0)
                            @foreach ($posts as $data)
                                <tr>
                                    <td>{{ $data->id }}</td>
                                    <td>
                                      <div style="max-width: 123px; max-height: 70px; overflow: hidden;">
                                        <img src="{{asset('$data->image')}}" class="img-fluid" alt="{{$data->image}}">                                        
                                      </div>
                                    </td>
                                    <td width="400px">{{ $data->title }}</td>
                                    <td>
                                    @foreach ($data->tags as $tag)
                                        <span class="badge badge-primary">{{$tag->name}}</span>
                                    @endforeach
                                    </td>
                                    <td>{{ $data->category->name }}</td>
                                    <td>{{ $data->user ? $data->user->name : '' }}</td>
                                    <td class="d-flex">
                                        <a href="{{ route('post.show', [$data->id]) }}"
                                            class="btn btn-sm btn-success mr-1"><i class="fas fa-eye"></i></a>
                                        <a href="{{ route('post.edit', [$data->id]) }}"
                                            class="btn btn-sm btn-primary mr-1"><i class="fas fa-edit"></i></a>
                                        <form action="{{ route('post.destroy', [$data->id]) }}}" class="mr-1"
                                            method="POST">
                                            @method('DELETE')
                                            @csrf
                                            <button class="btn btn-sm btn-danger "><i class="fas fa-trash"></i></button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            @else
                                <tr>
                                    <td colspan="5">
                                        <h5 class="text-center">No post found</h5>
                                    </td>
                                </tr>
                            @endif
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
    </div>
    <!-- /.card -->
    </div>
    <div>
    @endsection

resources/views/admin/post/show.blade.php
@extends('layouts.admin')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">post List</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('blog-home') }}">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v1</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="d-flex justify-content-between item-center">
                    <h3 class="card-title">post List</h3>
                    <a href="{{ route('post.index') }}" class="btn btn-primary">Back to Post</a>
                </div>
            </div>
            <!-- /.card-header -->
            <div class="card-body p-0">
                <table class="table">
                        <tr>
                            <th>Image</th>
                            <td>
                                <div style="max-width: 400px; max-height: 400px; overflow: hidden;">
                                    <img src="{{ asset('public/post/' . $post->image) }}" class="img-fluid"
                                        alt="{{ $post->image }}">
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <th style="width: 10px">ID</th>
                            <td>{{ $post->id }}</td>
                        </tr>
                        <tr>
                            <th>Title</th>
                            <td>{{ $post->title }}</td>
                        </tr>
                        <tr>
                            <th>Tag's</th>
                            <td>
                            @foreach ($post->tags as $tag)
                                <span class="badge badge-primary">{{ $tag->name }}</span>
                            @endforeach
                            </td>
                        </tr>
                        <tr>
                            <th>Categroy</th>
                            <td>{{ $post->category->name}}</td>
                        </tr> 
                        <tr>
                            <th style="">Description</th>
                            <td>{{ $post->description }}</td>
                        </tr>
                        <tr>
                            <th>Author</th>
                            <td>{{ $post->user ? $post->user->name : '' }}</td>
                        </tr> 
                        <tr>
                            <th>Action</th>
                            <td class="d-flex">
                                <a href="{{ route('post.edit', [$post->id]) }}" class="btn btn-sm btn-primary mr-1"><i
                                        class="fas fa-edit"></i></a>
                                
                                <form action="{{ route('post.destroy', [$post->id]) }}}" class="mr-1"
                                    method="POST">
                                    @method('DELETE')
                                    @csrf
                                    <button class="btn btn-sm btn-danger "><i class="fas fa-trash"></i></button>
                                </form>
                            </td>
                        </tr>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
    </div>
    <!-- /.card -->
    </div>
    <div>
    @endsection