routes/web.php
<?php

use App\Models\Post;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TagController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\FrontEndController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\ContactController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layouts.master');
});
// Route::get('/post', function () {
//     return view('website.contact');
// });

Auth::routes();
//forntend controller
Route::get('/home',[FrontEndController::class, 'home'])->name('website.home');
Route::get('/about',[FrontEndController::class, 'about'])->name('website.about');
Route::get('/category/{slug?}',[FrontEndController::class, 'category'])->name('website.category');
Route::get('/contact',[FrontEndController::class, 'contact'])->name('website.contact');
Route::post('/contactStore',[FrontEndController::class, 'sendMessage'])->name('contact.store');
Route::get('/post/{slug?}',[FrontEndController::class, 'post'])->name('website.post');
Route::get('/userDetails/{slug?}',[FrontEndController::class, 'userDetails'])->name('website.userDetails');
Route::get('/blog-home',[IndexController::class,'index'])->name('blog-home');



// admin panel route
Route::group(['prefix'=>'admin', 'middleware'=>['auth']], function(){
    Route::get('/test', function () {
        return view('admin.dashboard.index');
    });
    Route::get('/delete',[ContactController::class,'delete'])->name('contact.destroy');
    Route::resource('/category',CategoryController::class);
    Route::resource('/tag',TagController::class);
    Route::resource('/post',PostController::class);
    Route::resource('/user',UserController::class);
    Route::resource('/contacts',ContactController::class);

    Route::get('/profile',[UserController::class,'profile'])->name('user.profile');
    Route::get('/setting',[SettingController::class,'index'])->name('setting.index');
    Route::post('/settingUpdate',[SettingController::class,'update'])->name('setting.update');
    Route::get('/imageCreate',[\App\Http\Controllers\MultipleImageController::class,'create'])->name('multipleImage.create');
    Route::post('/multipleImage',[\App\Http\Controllers\MultipleImageController::class,'Store'])->name('multipleImage.store');
    //message Route

    Route::get('/contactShow/{id}',[\App\Http\Controllers\ContactController::class,'show'])->name('contact.show');
});
Route::get('/logout', function(){
    Auth::logout();
    return Redirect::to('login');
 });
Route::get('/test',function(){
    $posts = Post::all();
    $id =172;
    foreach($posts as $post){
        $post->image = "https://picsum.photos/id/".$id."/640/480.jpg";
        $post->update();
        $id++;
    }
    return $posts;
});
Route::get('/clear', function(){
    \Artisan::call('route:clear');
    \Artisan::call('config:cache');
    \Artisan::call('cache:clear');
});

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use HasFactory;
    protected $guarded =['created_at','updated_at','deleted_at'];
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use Session;
use App\Models\Tag;
use Illuminate\Support\Str;
use Illuminate\Http\Request;
use App\Http\Requests\TagStoreRequest;
use App\Http\Requests\TagUpdateRequest;

class TagController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $tags = tag::orderBy('created_at','DESC')->paginate(20);
        return view('admin.tag.index',compact('tags'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tag.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TagStoreRequest $request)
    {
        $tag = $request->Validated();
        $tag = tag::create([
            'name' => $request->name,
            'slug'=> Str::slug($request->name,'_'),
            'description'=>$request->description,
        ]);
        Session::flash('status','Data Successfully iserted');
        return redirect('admin/tag/create');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function show(tag $tag)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function edit(tag $tag)
    {
       return view('admin.tag.edit',compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function update(TagUpdateRequest $request, tag $tag)
    {
        $data = $request->Validated();
        $data['slug'] = Str::slug($request->name,'_');
        $tag->update($data);
        Session::flash('status','Data Successfully updated');
        return redirect('admin/tag');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function destroy(tag $tag)
    {
      if ($tag) {
        $tag->delete();
        Session::flash('status','Data Successfully Deleted');
        return redirect('admin/tag');

      }
    }
}

resources/views/admin/tag/create.blade.php
@extends('layouts.admin')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Create Tag</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('blog-home') }}">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v1</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="d-flex justify-content-between item-center">
                    <h3 class="card-title">Create Tag</h3>
                    <a href="{{ URL::to('admin/tag') }}" class="btn btn-primary">Tag List</a>
                </div>
            </div>
<!--             @if (Session::has('status'))
                <p class="alert alert-success">{{ Session::get('status') }}</p>
            @endif -->
            <div class="row">
                <div class="col-md-7">
                    <form method="POST" action="{{ route('tag.store') }}">
                        @csrf
                        <div class="card-body">
                            <div class="form-group">
                                <label for="exampleInputname">Name</label>
                                <input type="text" name="name" class="form-control" id="exampleInputName"
                                    placeholder="Enter tag Name">
                                @error('name')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="exampleInputDescription">Description</label>
                                <textarea name="description" id="" cols="60" rows="4" class="form-control"></textarea>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>

        <div>
        @endsection

resources/views/admin/tag/edit.blade.php
@extends('layouts.admin')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">Create tag</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('blog-home') }}">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v1</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="d-flex justify-content-between item-center">
                    <h3 class="card-title">tag Edit - {{$tag->name}}</h3>
                    <a href="{{ URL::to('admin/tag') }}" class="btn btn-primary">tag List</a>
                </div>
            </div>
<!--             @if (Session::has('status'))
                <p class="alert alert-success">{{ Session::get('status') }}</p>
            @endif -->
            <div class="row">
                <div class="col-md-7">
                    <form action="{{ route('tag.update',[$tag->id])}}" method="POST">
                        @csrf
                        @method('PUT')
                        <div class="card-body">
                            <div class="form-group">
                                <label for="exampleInputname">Name</label>
                                <input type="text" name="name" class="form-control" id="exampleInputName"
                                    placeholder="Enter tag Name" value="{{$tag->name}}">
                                @error('name')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="exampleInputDescription">Description</label>
                                <textarea name="description" id="" cols="60" rows="4" class="form-control" value="{{$tag->description}}"></textarea>
                            </div>
                        </div>
                        <div class="card-footer">
                            <button type="submit" class="btn btn-primary">Update</button>
                        </div>
                    </form>
                </div>
            </div>

        </div>

        <div>
        @endsection

resources/views/admin/tag/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">tag List</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{route('blog-home')}}">Home</a></li>
                    <li class="breadcrumb-item active">Dashboard v1</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="d-flex justify-content-between item-center">
                <h3 class="card-title">tag List</h3>
                <a href="{{route('tag.create')}}" class="btn btn-primary">Create tag</a>
            </div>

            <!-- <div class="card-tools">
                <ul class="pagination pagination-sm float-right">
                    <li class="page-item"><a class="page-link" href="#">«</a></li>
                    <li class="page-item"><a class="page-link" href="#">1</a></li>
                    <li class="page-item"><a class="page-link" href="#">2</a></li>
                    <li class="page-item"><a class="page-link" href="#">3</a></li>
                    <li class="page-item"><a class="page-link" href="#">»</a></li>
                </ul>
            </div> -->
        </div>
        <!-- /.card-header -->
        <div class="card-body p-0">
            <table class="table">
                <thead>
                    <tr>
                        <th style="width: 10px">ID</th>
                        <th>Name</th>
                        <th>Slug</th>
                        <th>Description</th>
                        <th>Post Count</th>
                        <th style="width: 40px">Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if ($tags->count()>0)
                        
                    
                  @foreach($tags as $data)
                    <tr>
                        <td>{{$data->id}}</td>
                        <td>{{$data->name}}</td>
                        <td>{{$data->slug}}</td>
                        <td>{{$data->description}}</td>
                        <td>{{$data->id}}</td>
                        <td class="d-flex">
                          <a href="{{route('tag.edit',[$data->id])}}" class="btn btn-sm btn-primary mr-1"><i class="fas fa-edit"></i></a>
                          <form action="{{route('tag.destroy',[$data->id])}}}" class="mr-1" method="POST">
                            @method('DELETE')
                            @csrf
                            <button class="btn btn-sm btn-danger "><i class="fas fa-trash"></i></button>
                          </form>
                    
                          <a href="{{route('tag.destroy',[$data->id])}}}" class="btn btn-sm btn-success mr-1"><i class="fas fa-eye"></i></a>
                        </td>
                    </tr>
                    @endforeach
                    @else
                        <tr>
                            <td colspan="5" class="text-center">
                                <h5>No Tag Found</h5>
                            </td>
                        </tr>
                    @endif
                </tbody>
            </table>
        </div>
        <!-- /.card-body -->
    </div>
</div>
<!-- /.card -->
</div>
<div>
    @endsection