routes/web.php
<?php

use App\Models\Post;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\TagController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PostController;
use App\Http\Controllers\AboutController;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\CategoryController;
use App\Http\Controllers\FrontEndController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\SettingController;
use App\Http\Controllers\ContactController;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('layouts.master');
});
// Route::get('/post', function () {
//     return view('website.contact');
// });

Auth::routes();
//forntend controller
Route::get('/home',[FrontEndController::class, 'home'])->name('website.home');
Route::get('/about',[FrontEndController::class, 'about'])->name('website.about');
Route::get('/category/{slug?}',[FrontEndController::class, 'category'])->name('website.category');
Route::get('/contact',[FrontEndController::class, 'contact'])->name('website.contact');
Route::post('/contactStore',[FrontEndController::class, 'sendMessage'])->name('contact.store');
Route::get('/post/{slug?}',[FrontEndController::class, 'post'])->name('website.post');
Route::get('/userDetails/{slug?}',[FrontEndController::class, 'userDetails'])->name('website.userDetails');
Route::get('/blog-home',[IndexController::class,'index'])->name('blog-home');



// admin panel route
Route::group(['prefix'=>'admin', 'middleware'=>['auth']], function(){
    Route::get('/test', function () {
        return view('admin.dashboard.index');
    });
    Route::get('/delete',[ContactController::class,'delete'])->name('contact.destroy');
    Route::resource('/category',CategoryController::class);
    Route::resource('/tag',TagController::class);
    Route::resource('/post',PostController::class);
    Route::resource('/user',UserController::class);
    Route::resource('/contacts',ContactController::class);

    Route::get('/profile',[UserController::class,'profile'])->name('user.profile');
    Route::get('/setting',[SettingController::class,'index'])->name('setting.index');
    Route::post('/settingUpdate',[SettingController::class,'update'])->name('setting.update');
    Route::get('/imageCreate',[\App\Http\Controllers\MultipleImageController::class,'create'])->name('multipleImage.create');
    Route::post('/multipleImage',[\App\Http\Controllers\MultipleImageController::class,'Store'])->name('multipleImage.store');
    //message Route

    Route::get('/contactShow/{id}',[\App\Http\Controllers\ContactController::class,'show'])->name('contact.show');
});
Route::get('/logout', function(){
    Auth::logout();
    return Redirect::to('login');
 });
Route::get('/test',function(){
    $posts = Post::all();
    $id =172;
    foreach($posts as $post){
        $post->image = "https://picsum.photos/id/".$id."/640/480.jpg";
        $post->update();
        $id++;
    }
    return $posts;
});
Route::get('/clear', function(){
    \Artisan::call('route:clear');
    \Artisan::call('config:cache');
    \Artisan::call('cache:clear');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'image',
        'description',
        'slug',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Post;
use Illuminate\Validation\Rule;
use Session;
class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::latest()->paginate(20);
        return view('admin.user.index',compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.user.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name'=>'unique:users,name',
            'email'=>'unique:users,email',
        ]);
        $create = User::create($request->all());
        return redirect()->back()->with('status','User succesfully added');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       $user = User::find($id);
        return view('admin.user.edit',compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name'=>['required',Rule::unique('users')->ignore($id)],
            'email'=>['required',Rule::unique('users')->ignore($id)],
        ]);
        User::find($id)->update($request->all());
        Session::flash('status','User SuccessFully updated');
        return redirect()->route('user.index');
    }
    public function profile(){
        $user = auth()->user();
        $posts = Post::all()->where('user_id', $user->id);
        return view('admin.user.profile',compact('user','posts'));
    } 

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        if($id)
        {
            $id->delete();
            Session::flash('status','User Successfully deleted');
            return redirect('admin.user.index');
        }
    }
}

resources/views/admin/user/create.blade.php
@extends('layouts.admin')
@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Create user</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('blog-home') }}">Home</a></li>
                    <li class="breadcrumb-item active">Dashboard v1</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="d-flex justify-content-between item-center">
                <h3 class="card-title">user Create</h3>
                <a href="{{ URL::to('admin/user') }}" class="btn btn-primary">user List</a>
            </div>
        </div>
        @if (Session::has('status'))
        <p class="alert alert-success">{{ Session::get('status') }}</p>
        @endif
        <div class="card-body p-0">
        <div class="row">
            <div class="col-12 col-lg-6 offset-lg-3 col-md-8 offset-md-2">
                <form method="POST" action="{{ route('user.store') }}" enctype="multipart/form-data">
                    @csrf
                    @method('POST')
                    @include('admin.user.user-form',['button'=>'Save'])
                </form>
            </div>
        </div>
    </div>
</div>

<div>
    @endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.admin')
@section('content')
<div class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1 class="m-0">Create user</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="{{ route('blog-home') }}">Home</a></li>
                    <li class="breadcrumb-item active">Dashboard v1</li>
                </ol>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="d-flex justify-content-between item-center">
                <h3 class="card-title">user Edit - {{$user->name}}</h3>
                <a href="{{ URL::to('admin/user') }}" class="btn btn-primary">user List</a>
            </div>
        </div>
        @if (Session::has('status'))
        <p class="alert alert-success">{{ Session::get('status') }}</p>
        @endif
        <div class="card-body p-0">
            <div class="row">
                <div class="col-12 col-lg-6 offset-lg-3 col-md-8 offset-md-2">
                    <form action="{{ route('user.update',[$user->id])}}" method="POST" enctype="multipart/form-data">
                        @csrf
                        @method('PUT')
                        @include('admin.user.user-form',['button'=>'Update'])
                    </form>
                </div>
            </div>
        </div>
    </div>
        @endsection

resources/views/admin/user/index.blade.php
@extends('layouts.admin')
@section('content')
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0">User</h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{ route('blog-home') }}">Home</a></li>
                        <li class="breadcrumb-item active">Dashboard v1</li>
                    </ol>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="card">
            <div class="card-header">
                <div class="d-flex justify-content-between item-center">
                    <h3 class="card-title">User List</h3>
                    <a href="{{ route('user.create') }}" class="btn btn-primary">Add New User</a>
                </div>

                <!-- <div class="card-tools">
                    <ul class="pagination pagination-sm float-right">
                        <li class="page-item"><a class="page-link" href="#">«</a></li>
                        <li class="page-item"><a class="page-link" href="#">1</a></li>
                        <li class="page-item"><a class="page-link" href="#">2</a></li>
                        <li class="page-item"><a class="page-link" href="#">3</a></li>
                        <li class="page-item"><a class="page-link" href="#">»</a></li>
                    </ul>
                </div> -->
            </div>
            <!-- /.card-header -->
            <div class="card-body p-0">
                <table class="table">
                    <thead>
                        <tr>
                            <th style="width: 10px">ID</th>
                            <th>Name</th>
                            <th>Email</th>
                            <th>Image</th>
                            <th>Password</th>
                            <th>Status</th>
                            <th style="width: 40px">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @if ($users->count() > 0)
                            @foreach ($users as $data)
                                <tr>
                                    <td>{{ $data->id }}</td>
                                    <td>{{ $data->name }}</td>
                                    <td>{{ $data->email }}</td>
                                    <td>
                                      <div style="max-width: 123px; max-height: 70px; overflow: hidden;">
                                        <img src="{{asset('images/img_4.jpg')}}" class="img-fluid" alt="">                                        
                                      </div>
                                    </td>
                                    <td  style="max-width:200px;">{{ $data->password }}</td>
                                    <td>
                                    1
                                    </td>
                                    <td class="d-flex">
                                        <a href="{{ route('user.show', [$data->id]) }}"
                                            class="btn btn-sm btn-success mr-1"><i class="fas fa-eye"></i></a>
                                        <a href="{{ route('user.edit', [$data->id]) }}"
                                            class="btn btn-sm btn-primary mr-1"><i class="fas fa-edit"></i></a>
                                        <form action="{{ route('user.destroy', [$data->id]) }}}" class="mr-1"
                                            method="user">
                                            @method('DELETE')
                                            @csrf
                                            <button class="btn btn-sm btn-danger "><i class="fas fa-trash"></i></button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            @else
                                <tr>
                                    <td colspan="5">
                                        <h5 class="text-center">No user found</h5>
                                    </td>
                                </tr>
                            @endif
                    </tbody>
                </table>
            </div>
            <!-- /.card-body -->
        </div>
    </div>
    <!-- /.card -->
    </div>
    <div>

@endsection

resources/views/admin/user/user-form.blade.php
<div class="card-body">
    <div class="form-group">
        <label for="exampleInputname">Name</label>
        <input type="text" name="name" class="form-control" id="exampleInputName" placeholder="Enter user Name"
            value="{{ isset($user) ? $user->name : old('name')}}">
        @error('name')
        <span class="text-danger">{{ $message }}</span>
        @enderror
    </div>
    <div class="form-group">
        <label for="exampleInputname">Email</label>
        <input type="email" name="email" class="form-control" id="exampleInputName" placeholder="Enter user email"
            value="{{ isset($user) ? $user->email : old('email')}}">
        @error('email')
        <span class="text-danger">{{ $message }}</span>
        @enderror
    </div>
    <div class="form-group">
        <label for="exampleInputname">Password</label>
        <input type="password" name="password" class="form-control" id="exampleInputName"
            placeholder="Enter user password" value="{{ isset($user) ? $user->password : old('password')}}">
        @error('password')
        <span class="text-danger">{{ $message }}</span>
        @enderror
    </div>
    <div class="form-group">
        <label for="exampleInputname">Image</label>
        <input type="file" name="image" class="form-control" id="exampleInputName" placeholder="Enter user image"
            value="{{ isset($user) ? $user->image : old('image')}}">
        @error('image')
        <span class="text-danger">{{ $message }}</span>
        @enderror
    </div>
    <div class="form-group">
        <label for="exampleInputDescription">Description</label>
        <textarea name="description" id="" cols="60" rows="4"
            class="form-control">{{isset($user)? $user->description : old('description')}}</textarea>
    </div>
</div>
<div class="card-footer">
    <button type="submit" class="btn btn-primary">{{$button}}</button>
</div>